* formats

g Label = "% HH that report a reduction of income by source: AGRICULTURE ACTIVITIES (current v. pre pandemic)" if Indicador == "agrinc_loss"
replace Label = "Percentage of children who engage in education/learning activities over the week of reference" if Indicador == "asiste"
replace Label = "Percentage of children (06-17) who attend school before pandemic " if Indicador == "asiste_pre"
replace Label = "Percentage of population who had a job but did not work in the week of reference" if Indicador == "ausente"
replace Label = "% HH that report a reduction of income by source: BUSINESS (current v. pre pandemic)" if Indicador == "businessinc_loss"
replace Label = "% of large-medium establishment workers pre pandemic who moved  to small-micro establishments" if Indicador == "cambio_peque_micro"
replace Label = "Unemployment rate - Percetage of the economicaly active population who where unemployed in the week of reference" if Indicador == "desocupado1"
replace Label = "Percentage of children (06-17) who attend school before pandemic but did not engage in education/learning activities over the week of reference" if Indicador == "dropper"
replace Label = "% of employed population by size of establisment: LARGE (pre pandemic)" if Indicador == "emp_tam0_grande"
replace Label = "% of employed population by size of establisment: MEDIUM (pre pandemic)" if Indicador == "emp_tam0_mediana"
replace Label = "% of employed population by size of establisment: MICRO (pre pandemic)" if Indicador == "emp_tam0_micro"
replace Label = "% of employed population by size of establisment: SMALL (pre pandemic)" if Indicador == "emp_tam0_peque"
replace Label = "% of employed population by size of establisment: LARGE (current)" if Indicador == "emp_tam1_grande"
replace Label = "% of employed population by size of establisment: MEDIUM (current)" if Indicador == "emp_tam1_mediana"
replace Label = "% of employed population by size of establisment: SMALL (current)" if Indicador == "emp_tam1_pequena"
replace Label = "% of employed population by size of establisment: MICRO (current)" if Indicador == "emp_tam1_micro"
replace Label = "% of formal workers pre pandemic who became informal" if Indicador == "for0_inf1"
replace Label = "Percentage of people reporting feeling anxious" if Indicador == "h_anxious"
replace Label = "" if Indicador == "h_other"
replace Label = "" if Indicador == "h_unvac_not_effective"
replace Label = "" if Indicador == "h_unvac_not_risk"
replace Label = "Percentage of unvaccinated people who do not intend to get vaccinated because the vaccines are not safe" if Indicador == "h_unvac_not_safe"
replace Label = "Percentage of unvaccinated people " if Indicador == "h_unvaccinated"
replace Label = "" if Indicador == "h_unvaccinated_no_intent"
replace Label = "Average working hours per week (pre pandemic)" if Indicador == "horas0"
replace Label = "Average working hours per week (current)" if Indicador == "horas1"
replace Label = "" if Indicador == "i_household_cct_0"
replace Label = "" if Indicador == "i_household_cct_1"
replace Label = "" if Indicador == "i_household_ps_cct"
replace Label = "" if Indicador == "income_loss_per"
replace Label = "" if Indicador == "income_loss_tot"
replace Label = "Percentage of informal employment prepandemic - Measured as employed people who in their ocupation did not contribute to the country's insurance schema" if Indicador == "informal0"
replace Label = "Percentage of informal employment - Measured as employed people who in their ocupation did not contribute to the country's insurance schema" if Indicador == "informal1"
replace Label = "" if Indicador == "no_eat_money"
replace Label = "Percentage of households without food because of lack of money or other resources" if Indicador == "no_food_money"
replace Label = "% households that ran out of food [pre pandemic, feb-2020]" if Indicador == "no_food_money_pre"
replace Label = "" if Indicador == "no_nutrish_food_money"
replace Label = "% of workers who kept their pre pandemic job but don't work from home " if Indicador == "noremotew"
replace Label = "% of workers who kept their pre pandemic job and don't work from home due to lack of devices to do so" if Indicador == "noremotew_device"
replace Label = "% of workers who kept their pre pandemic job and don't work from home due to the emplyer did not allow it" if Indicador == "noremotew_employer"
replace Label = "% of workers who kept their pre pandemic job and don't work from home due to lack of internet " if Indicador == "noremotew_internet"
replace Label = "% of workers who kept their pre pandemic job and don't work from home due to the type of job did not allow it" if Indicador == "noremotew_job_not_allow"
replace Label = "% of workers who kept their pre pandemic job and don't work from home due to other reasons" if Indicador == "noremotew_other"
replace Label = "% of people who were employed pre pandemic and became unemployed" if Indicador == "ocu0_desoc1"
replace Label = "% of people who wher employed pre pandemic and left the labor force" if Indicador == "ocu0_inac1"
replace Label = "% of people who change their pre-pandemic ocupation " if Indicador == "ocu0_ocu1"
replace Label = "Employment rate in the week of reference - measured as the percentage of population who worked in the week of reference" if Indicador == "ocup1"
replace Label = "Employment rate prepandemic" if Indicador == "ocupado0"
replace Label = "Employment rate in the week of reference - measured as the percentage of population who worked or had a job in the week of reference" if Indicador == "ocupado1"
replace Label = "% of people who lost their pre-pandemic job (18+ years old)" if Indicador == "perdida01"
replace Label = "% of workers who kept their pre pandemic job but work from home (proportion of remote hours = 100%)" if Indicador == "remotew"
replace Label = "% of employed population by economic sector: agriculture (current)" if Indicador == "rama_agricultura"
replace Label = "% of employed population by economic sector: agriculture (prepandemic)" if Indicador == "rama_agricultura_pre"
replace Label = "% of employed population by economic sector: contruction (current)" if Indicador == "rama_construccion"
replace Label = "% of employed population by economic sector: contruction (prepandemic)" if Indicador == "rama_construccion_pre"
replace Label = "% of employed population by economic sector: manufacture (current)" if Indicador == "rama_industria"
replace Label = "% of employed population by economic sector: manufacture (prepandemic)" if Indicador == "rama_industria_pre"
replace Label = "% of employed population by economic sector: services (current)" if Indicador == "rama_servicios"
replace Label = "% of employed population by economic sector: services (prepandemic)" if Indicador == "rama_servicios_pre"
replace Label = "% of employed population by type: WAGE WORKER (pre pandemic)" if Indicador == "tipoe_new0_asalariado"
replace Label = "% of employed population by type: SELF EMPLOYED (pre pandemic)" if Indicador == "tipoe_new0_cuentap"
replace Label = "% of employed population by type: EMPLOYER (pre pandemic)" if Indicador == "tipoe_new0_empleador"
replace Label = "% of employed population by type: OTHER (pre pandemic)" if Indicador == "tipoe_new0_otros"
replace Label = "% of employed population by type: WAGE WORKER (current)" if Indicador == "tipoe_new1_asalariado"
replace Label = "% of employed population by type: SELF EMPLOYED (current)" if Indicador == "tipoe_new1_cuentap"
replace Label = "% of employed population by type: EMPLOYER (current)" if Indicador == "tipoe_new1_empleador"
replace Label = "% of employed population by type: OTHER (current)" if Indicador == "tipoe_new1_otros"
replace Label = "% HH that report reduction of income from Regular Government Transfers (during v. pre pandemic)" if Indicador == "transfer_loss"
replace Label = "% HH that report a reduction of income by source: WAGE (current v. pre pandemic)" if Indicador == "wageinc_loss"
replace Label = "% of wage worker pre pandemic who became self-emplyed, employer or other" if Indicador == "wage0_oth1"
replace Label = "Share of respondents who are not planning to get vaccinated (vaccination reluctancy)" if Indicador == "h_unvaccinated_no_intent"
replace Label = "Respondent does not think they are effective" if Indicador == "h_unvac_not_effective"
replace Label = "Respondent declares he is not at risk of getting covid-19" if Indicador == "h_unvac_not_risk"
replace Label = "" if Indicador == "h_other"
replace Label = "% households where an adult did not eat for an entire day [last 30 days]" if Indicador == "no_eat_money"
replace Label = "% households where an adult could not eat healthy and nutritious food [last 30 days]" if Indicador == "no_nutrish_food_money"
replace Label = "" if Indicador == "i_household_ps_cct"
replace Label = "% HH that RECEIVED Regular Government Transfers (pre pandemic)" if Indicador == "i_household_cct_0"
replace Label = "% HH that RECEIVED Regular Government Transfers (during the pandemic)" if Indicador == "i_household_cct_1"
replace Label = "" if Indicador == "income_loss_per"
replace Label = "" if Indicador == "income_loss_tot"
replace Label = "Share of HHs with internet access (wifi)" if Indicador == "internet_wifi"
replace Label = "% inactive pre pandemic and became employed" if Indicador == "ina0_ocu1"
replace Label = "% inactive pre pandemic and became and informal worker" if Indicador == "ina0_ocu1_in"
replace Label = "% inactive pre pandemic and became unemployed" if Indicador == "ina0_desocu1"
replace Label = "Labour Force Participation LFP prepandemic" if Indicador =="activo0"
replace Label = "Labour Force Participation LFP 2021" if Indicador =="activo1"

g 			Country = "Antigua y Barbuda" 	if Pais == "268"
replace 	Country = "Belize" 				if Pais == "501"
replace 	Country = "Guatemala" 			if Pais == "502"
replace 	Country = "El Salvador" 		if Pais == "503"
replace 	Country = "Honduras" 			if Pais == "504"
replace 	Country = "Costa Rica" 			if Pais == "506"
replace 	Country = "Panama" 				if Pais == "507"
replace 	Country = "Haiti" 				if Pais == "509"
replace 	Country = "Peru" 				if Pais == "510"
replace 	Country = "Mexico" 				if Pais == "520"
replace 	Country = "Argentina" 			if Pais == "540"
replace 	Country = "Nicaragua" 			if Pais == "550"
replace 	Country = "Chile" 				if Pais == "560"
replace 	Country = "Colombia" 			if Pais == "580"
replace 	Country = "Bolivia" 			if Pais == "591"
replace 	Country = "Guyana" 				if Pais == "592"
replace 	Country = "Ecuador" 			if Pais == "593"
replace 	Country = "Paraguay" 			if Pais == "595"
replace 	Country = "Uruguay" 			if Pais == "598"
replace 	Country = "Santa Lucia" 		if Pais == "758"
replace 	Country = "Dominica" 			if Pais == "767"
replace 	Country = "Rep. Dominicana" 	if Pais == "809"
replace 	Country = "Jamaica" 			if Pais == "876"




